# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  networking.hostName = "rlucas-nixos";

  boot.initrd.availableKernelModules = ["xhci_pci" "thunderbolt" "nvme" "usbhid" "usb_storage" "sd_mod" "rtsx_pci_sdmmc"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = [
    "kvm-intel"
    "ddcci_backlight"
  ];
  boot.extraModulePackages = with config.boot.kernelPackages; [
    ddcci-driver
  ];

  

  # boot.kernelPatches = lib.singleton {
  #   name = "rt";
  #   patch = null;
  #   structuredExtraConfig = {
  #     EXPERT = lib.kernel.yes;
  #     PREEMPT_RT = lib.kernel.yes;
  #     PREEMPT_VOLUNTARY = lib.kernel.unset;
  #     PREEMPT_DYNAMIC = lib.kernel.unset;
  #   };
  # };


  fileSystems."/" = {
    device = "/dev/disk/by-uuid/38000cb8-9c8f-4922-bd8e-538a50e24c19";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/201A-940A";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s13f0u2u2.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
